# Generated by Django 3.2.6 on 2021-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresults',
            name='polling_unit',
            field=models.IntegerField(db_column='polling_unit_uniqueid'),
        ),
    ]
